apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: collaboration-service
  name: collaboration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collaboration-service
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: collaboration-service
    spec:
      containers:
      - image: asdfghjklxd/peerprep-collaboration-service:IMAGE_TAG
        imagePullPolicy: Always
        name: collaboration-service
        ports:
          - containerPort: 8004
        resources:
          limits:
            cpu: 400m
        env:
        - name: HOST
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_HOST
              name: peerprep-secrets
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_PORT
              name: peerprep-secrets
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_REDIS_HOST
              name: peerprep-secrets
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_REDIS_PORT
              name: peerprep-secrets
        - name: QUESTION_SERVICE_ENDPOINT
          valueFrom:
            secretKeyRef:
              key: COLLABORATION_SERVICE_QUESTION_SERVICE_ENDPOINT
              name: peerprep-secrets

---

kind: Service
apiVersion: v1
metadata:
  name: collaboration-service
spec:
  selector:
    app: collaboration-service
  ports:
    - name: collaboration-service
      protocol: TCP
      port: 8004
      targetPort: 8004

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: collaboration-service
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: collaboration-service
  targetCPUUtilizationPercentage: 80
